// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null } = {
	evm: "0x253028394517e27a6d22233e94b5b53c62926940",
	pvm: "0x1e1413be200b525a75a105a892c5d6f25044ef90",
};
