export const aperioRegistryAbi = [
  {
    type: "function",
    name: "createRepo",
    inputs: [
      { name: "organization", type: "string" },
      { name: "name", type: "string" },
      { name: "initialHeadCommit", type: "bytes32" },
      { name: "initialHeadCid", type: "string" },
      { name: "permissionlessContributions", type: "bool" },
    ],
    outputs: [{ name: "repoId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitProposal",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "proposedCommit", type: "bytes32" },
      { name: "proposedCid", type: "string" },
    ],
    outputs: [{ name: "proposalId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reviewProposal",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "proposalId", type: "uint256" },
      { name: "approved", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mergeProposal",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "proposalId", type: "uint256" },
      { name: "finalCommitHash", type: "bytes32" },
      { name: "finalCid", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setContributorRole",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "account", type: "address" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setReviewerRole",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "account", type: "address" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRepo",
    inputs: [{ name: "repoId", type: "bytes32" }],
    outputs: [
      { name: "maintainer", type: "address" },
      { name: "headCommit", type: "bytes32" },
      { name: "headCid", type: "string" },
      { name: "proposalCount", type: "uint256" },
      { name: "releaseCount", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRepoMetadata",
    inputs: [{ name: "repoId", type: "bytes32" }],
    outputs: [
      { name: "organization", type: "string" },
      { name: "name", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProposal",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "proposalId", type: "uint256" },
    ],
    outputs: [
      { name: "contributor", type: "address" },
      { name: "proposedCommit", type: "bytes32" },
      { name: "proposedCid", type: "string" },
      { name: "approvals", type: "uint256" },
      { name: "rejections", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "mergedCommit", type: "bytes32" },
      { name: "mergedCid", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPermissionlessContributions",
    inputs: [{ name: "repoId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasContributorRole",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasReviewerRole",
    inputs: [
      { name: "repoId", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
];
